---
# http://projects.theforeman.org/issues/18818
- name: Workaround 18818
  command: >
    foreman-installer --scenario "{{ foreman_installer_scenario }}" --migrations-only > /dev/null
  changed_when: False
  when: foreman_installer_scenario == "foreman-proxy-content"

- name: restart httpd
  service:
    name: httpd
    state: restarted

- name: 'set foreman_installer_update_certs to True'
  set_fact:
    foreman_installer_update_certs: True
  when: certs_stat.results[0].stat.exists or certs_stat.results[1].stat.exists or certs_stat.results[2].stat.exists

- name: 'set dont_save_answers to False'
  set_fact:
    dont_save_answers: False

- name: write answers file
  template:
    src: templates/scenario-answers.yaml.j2
    dest: "/etc/foreman-installer/scenarios.d/{{ foreman_installer_scenario }}-answers.yaml"
    owner: root
    group: root
    mode: 0600
  notify:
    - reload ansible_local

- name: execute foreman-installer
  command: >
      foreman-installer {{ (foreman_installer_verbose == True) | ternary("-v", "") }}
      --scenario "{{ foreman_installer_scenario }}"
      {{ (dont_save_answers == True) | ternary("--dont-save-answers", "") }}
      {{ (foreman_installer_update_certs == True and foreman_installer_update_certs_tar == False) | ternary("--certs-update-server --certs-update-server-ca", "") }}
      {{ (foreman_installer_update_certs == True and foreman_installer_update_certs_tar == True) | ternary("--certs-update-server", "") }}
      {{ (foreman_installer_upgrade == True and (foreman_installer_scenario == "katello" or foreman_installer_scenario == "satellite")) | ternary("--upgrade", "") }}
      {{ foreman_installer_options | join(" ") }}

- name: reload ansible_local
  setup:
    filter: ansible_local

- name: rewrite answers file
  template:
    src: templates/scenario-answers.yaml.j2
    dest: "/etc/foreman-installer/scenarios.d/{{ foreman_installer_scenario }}-answers.yaml"
    owner: root
    group: root
    mode: 0600
  notify:
    - reload ansible_local
